services:
  db:
    image: ankane/pgvector:latest
    container_name: book_scraper_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - book_scraper_data:/var/lib/postgresql/data
    restart: unless-stopped

api:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: books_api
   command: uvicorn api.main:app --host 0.0.0.0 --port 8000
   ports:
     - "8000:8000"
   depends_on:
      - db

scraper:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: book_scraper
  command: python scripts/scraper.py
  depends_on:
    - db

volumes:
  book_scraper_data: